version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - my_db_volume:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080" 
    restart: always

volumes:
  my_db_volume:
